![Accel.AI](https://github.com/kaopanboonyuen/2110446_DataScience_2021s2/raw/main/%20files/accelai.png)

In [1]:
# First, we need to import the package NumPy, which is the library enabling all the fun with algebraic structures.
import numpy as np

# Numpy Array VS Python List

In [2]:
# The Test to see that numpy is faster than pure python.

import time
import numpy as np

size_of_vec = 1000000 #1M

def pure_python():
    t1 = time.time()
    x = range(size_of_vec)
    y = range(size_of_vec)
    z = [x[i] + y[i] for i in range (len(x))]
    t2 = time.time()
    used_time = t2-t1
    print(used_time,'seconds')
    return used_time

def numpy_version():
    t1 = time.time()
    x = np.arange(size_of_vec)
    y = np.arange(size_of_vec)
    z = x+y
    t2 = time.time()
    used_time = t2-t1
    print(used_time,'seconds')
    return used_time

t1 = pure_python()
t2 = numpy_version()
print('faster', t1 - t2, 'seconds')
print('faster', t1/t2, 'times')

0.11324000358581543 seconds
0.004964351654052734 seconds
faster 0.1082756519317627 seconds
faster 22.81063298434348 times


# Vectors and Matrices

Using NumPy we can define vectors and matrices with both real or complex elements. Although, in contrast to Matlab, where matrix is the default type, in Python we need to define vectors and matrices as `array` or `matrix` type from NumPy package.

## Create Numpy Array

### 1D Array

In [3]:
a = np.array([10,20,30])   # Define a vector of size 3 using type 'array'
print(a)
print(a.shape)          # Size/shape of vector

[10 20 30]
(3,)


### 2D Array or Matrix

In [4]:
b = np.array([[10,20,30],[40,50,60]])  # Define a vector of size 3 using type 'matrix'
print(b)
print(b.shape)          # Size/shape of vector

[[10 20 30]
 [40 50 60]]
(2, 3)


### Essetial Matrix

In [5]:
print('3x3 Matrix full of zeros:')
print(np.zeros([3,3]))

print('\n3x3 Matrix full of ones:')
print(np.ones([3,3]))

print('\n3x3 identity matrix:')
print(np.eye(3))

print('\n3x3 diagonal matrix:')
x = np.array([1.,2.,3.])
print(np.diag(x))

print('\n3x3 random matrix:')
print(np.random.rand(3,3))

3x3 Matrix full of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

3x3 Matrix full of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3x3 diagonal matrix:
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]

3x3 random matrix:
[[0.42912744 0.25528077 0.60750569]
 [0.73260045 0.84125654 0.35639727]
 [0.10122302 0.90111068 0.41832668]]


## Indexing

Note that matrix and array elements in Python are indexed from 0, in contrast to Matlab where indexing starts from 1.

**_Matrices_** can be defined as 2D arrays of type `array` or `matrix` (there is no problem with transposition with any type).

In [6]:
# 1D indexing
print(a)
print(a[:])
print(a[0])
print(a[1:])
print(a[:-1])

[10 20 30]
[10 20 30]
10
[20 30]
[10 20]


In [7]:
# 2D indexing
print(b)
print(b[1,1])

print(b[:])     # Get all elements
print(b[0])     # The first element
print(b[-1])    # The last element
print(b[:3])    # The first 3 rows
print(b[-3:])   # The last 3 rows
print(b[2:4])   # 2:4 selects elements of indexes 2 and 3

[[10 20 30]
 [40 50 60]]
50
[[10 20 30]
 [40 50 60]]
[10 20 30]
[40 50 60]
[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]
[]


# Functions

## Arange and Linspace

In [8]:
c = np.arange(10,20,2)   # Define vector from 10 to 20 with step 2
print(c)

[10 12 14 16 18]


In [9]:
c = np.linspace(10,20,6)   # Define vector as 6 values evenly spaced from 10 to 20
print(c)

[10. 12. 14. 16. 18. 20.]


## Random

In [10]:
print(np.random.rand(4))

[0.26342794 0.21540646 0.6295201  0.49133883]


In [11]:
print(np.random.rand(4,5))

[[0.87634729 0.11160122 0.75620501 0.90058536 0.34366862]
 [0.26367077 0.36919197 0.14982941 0.21238542 0.59609454]
 [0.85538    0.25574707 0.66284681 0.47484248 0.64795519]
 [0.54355594 0.45896525 0.52131492 0.82702953 0.91339767]]


In [12]:
# Random array of int, size=3, value 0-9
print(np.random.randint(10, size=(3)))

[8 1 1]


## Basic Array Operations

In [13]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


### Working with Scalar

In [14]:
print(x+2)

[[3 4]
 [5 6]]


In [15]:
print(x*2)

[[2 4]
 [6 8]]


### Working with 2 Vectors

In [16]:
print(x+y)

[[ 6  8]
 [10 12]]


In [17]:
print(y-x)

[[4 4]
 [4 4]]


In [18]:
print(x*y) # element-wise multiplication

[[ 5 12]
 [21 32]]


In [19]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## Dot

**_Matrix multiplication_** must be executed by method for dot product `numpy.dot`. Operator `*` produces only element-wise multiplication in Python.

In [20]:
v = np.array([9,10])
w = np.array([11,12])

In [21]:
print('Matrix v\n', v)
print('=====================')
print('Matrix w\n', w)
print('=====================')
print('v.dot(w)\n', v.dot(w))
print('=====================')

Matrix v
 [ 9 10]
Matrix w
 [11 12]
v.dot(w)
 219


In [22]:
print('Matrix x\n', x)
print('=====================')
print('Matrix v\n', v)
print('=====================')
print('x.dot(v)\n', x.dot(v))
print('=====================')

Matrix x
 [[1 2]
 [3 4]]
Matrix v
 [ 9 10]
x.dot(v)
 [29 67]


In [23]:
print('Matrix x\n', x)
print('=====================')
print('Matrix y\n', y)
print('=====================')
print('x.dot(y)\n', x.dot(y))
print('=====================')

Matrix x
 [[1 2]
 [3 4]]
Matrix y
 [[5 6]
 [7 8]]
x.dot(y)
 [[19 22]
 [43 50]]


In [24]:
print('Matrix A:')
A = np.array([[11,12,13], [21,22,23], [31,32,33]])
print(A)

print('\nMatrix B:')
B = np.ones([3,3])
print(B)

print('\nElement-wise multiplication A*B:')
print(A*B)

print('\nMatrix multiplication A by B:')
print(np.dot(A,B))

print('\nMatrix multiplication B by A:')
print(np.dot(B,A))

Matrix A:
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Matrix B:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Element-wise multiplication A*B:
[[11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]

Matrix multiplication A by B:
[[36. 36. 36.]
 [66. 66. 66.]
 [96. 96. 96.]]

Matrix multiplication B by A:
[[63. 66. 69.]
 [63. 66. 69.]
 [63. 66. 69.]]


## Transpose

**_Transposition_** of vectors is not so intuitive as in Matlab, especially if a vector is defined as 1D `array` and you cannot distinguish between row and column vector. However, using the keyword `newaxis` it's possible to shape the vector into 2D array (as matrix of size $1 \times n$ or $n \times 1$), where transposition makes sense and can be obtained by attribute `.T`.

**_Matrix transposition_** is obtained by attribute `.T`

In [25]:
x = a[:, np.newaxis]  # Make column vector from vector a (defined as array)
print(x)
print(x.shape)    # Now size of column vector is 3x1
print(x.T)        # Make row vector by transpostion of column vector

[[10]
 [20]
 [30]]
(3, 1)
[[10 20 30]]


If a vector was defined as 2D array of type `matrix`, transportation is not a problem.

In [26]:
x = b.T           # Make column vector from vector b (defined as matrix)
print(x)
print(x.shape)    # Now size of column vector is 3x1
print(x.T)        # Make row vector by transpostion of column vector

[[10 40]
 [20 50]
 [30 60]]
(3, 2)
[[10 20 30]
 [40 50 60]]


In [27]:
X = np.ones([2,5])     # Generate 2x5 matrix full of ones
Y = X.T             # Obtain transpose of matrix X

print('Matrix X of size', X.shape, ':\n', X)
print('\nMatrix Y=X.T of size', Y.shape, ':\n', Y)

Matrix X of size (2, 5) :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Matrix Y=X.T of size (5, 2) :
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## VStack and HStack

In [28]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [29]:
print(np.vstack([ A, np.ones([1,3]) ]))  # Add row vector to matrix
print()
print(np.hstack([ A, np.ones([3,1]) ]))  # Add column vector to matrix
print()
print(np.hstack([ A, np.eye(3) ]))       # Merge two matrices horizontally

[[11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]
 [ 1.  1.  1.]]

[[11. 12. 13.  1.]
 [21. 22. 23.  1.]
 [31. 32. 33.  1.]]

[[11. 12. 13.  1.  0.  0.]
 [21. 22. 23.  0.  1.  0.]
 [31. 32. 33.  0.  0.  1.]]


## Other Matrix Features

There are also methods for essential matrix features like **_Frobenius norm_**, **_rank_** or **_determinant_**.

For a matrix \( A \) with elements \( a_{ij} \), the Frobenius norm \( ||A||_F \) is defined as:

### Frobenius Norm Formula

The Frobenius norm of a matrix \( A \) is defined as:


$$
\| A \|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n |a_{ij}|^2}
$$



where \( A \)is an \( m \times n \) matrix with elements \( a_{ij} \).

In [33]:
#  it is calculated as the square root of the sum of the absolute squares of its elements. Mathematically, it can be expressed as:

print('Matrix A of size', A.shape, ':\n', A)

# Frobenius norm of matrix
print('\nFrobenius norm: ||A|| =', np.linalg.norm(A))

# Rank of matrix
print('rank(A) =', np.linalg.matrix_rank(A))

# Determinant of matrix
print('det(A) =',  np.linalg.det(A))

Matrix A of size (3, 3) :
 [[11 12 13]
 [21 22 23]
 [31 32 33]]

Frobenius norm: ||A|| = 70.44146506142529
rank(A) = 2
det(A) = -3.387970907404506e-14


In example above, note that the matrix $\mathbf{A}$ is a singular matrix, because its rank is lower than number of its rows, thus also its detemninat is zero.

**_Euclidean norm_** of vector is returned by method `numpy.linalg.norm`

### Euclidean Norm Formula

The Euclidean norm of a vector \( \mathbf{x} \) is defined as:

$$
\| \mathbf{x} \| = \sqrt{\sum_{i=1}^n x_i^2}
$$

where \( \mathbf{x} \) is a vector with components \( x_1, x_2, \ldots, x_n \).


In [34]:
# The Euclidean norm of a square matrix is the square root of the sum of all the squares of the matrix's elements
norm = np.linalg.norm(a)      # Euclidean norm of vector a (Eucliean norm is also called L2 norm)
print('a =', a)
print('norm(a) =', norm)

x = a/np.linalg.norm(a)       # Make normalized/unit vector from a
print('x =', x)
print('norm(x) =', np.linalg.norm(x))

a = [10 20 30]
norm(a) = 37.416573867739416
x = [0.26726124 0.53452248 0.80178373]
norm(x) = 0.9999999999999999
